#!/usr/bin/env python3
"""Turn DejaVu Sans into Adafruit-GFX fonts (1-bit, same look as the Pi version).
Writes SkyTracker/fonts.h. Extra glyphs: \\x80 up-arrow, \\x81 down-arrow,
\\x82 degree, \\x83 middle dot, \\x84 ellipsis,
\\x85-\\x8A: Finnish/Swedish letters. Text is written in UTF-8 and mapped by utf8.h."""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "SkyTracker", "fonts.h")
DIRS = ["/usr/share/fonts/truetype/dejavu", "C:/Windows/Fonts", os.path.join(HERE, "fonts")]
FONTS = [  # C name, file, pixel size
    ("F_R11", "DejaVuSans.ttf", 11), ("F_R12", "DejaVuSans.ttf", 12),
    ("F_R13", "DejaVuSans.ttf", 13), ("F_R14", "DejaVuSans.ttf", 14),
    ("F_C12", "DejaVuSansCondensed.ttf", 12),
    ("F_B12", "DejaVuSans-Bold.ttf", 12), ("F_B13", "DejaVuSans-Bold.ttf", 13),
    ("F_B14", "DejaVuSans-Bold.ttf", 14), ("F_B15", "DejaVuSans-Bold.ttf", 15),
    ("F_B16", "DejaVuSans-Bold.ttf", 16), ("F_B18", "DejaVuSans-Bold.ttf", 18),
    ("F_B22", "DejaVuSans-Bold.ttf", 22), ("F_B26", "DejaVuSans-Bold.ttf", 26),
    ("F_B30", "DejaVuSans-Bold.ttf", 30), ("F_B34", "DejaVuSans-Bold.ttf", 34),
]
EXTRA = ["\u2191", "\u2193", "\u00b0", "\u00b7", "\u2026",  # 0x80-0x84
         "\u00e4", "\u00f6", "\u00e5", "\u00c4", "\u00d6", "\u00c5",  # 0x85-0x8A: ä ö å Ä Ö Å
         "\u0161", "\u0160", "\u017e", "\u017d"]  # 0x8B-0x8E: š Š ž Ž (Finnish transliteration)
FIRST, LAST = 0x20, 0x7F + len(EXTRA)


def find(name):
    for d in DIRS:
        p = os.path.join(d, name)
        if os.path.exists(p):
            return p
    raise SystemExit(f"font {name} not found")


def glyph_for(font, ch):
    if ch is None:
        return b"", (0, 0, 0, 0, 0, 0)
    size = font.size
    pad = size
    img = Image.new("L", (size * 4, size * 4), 0)
    d = ImageDraw.Draw(img)
    base = pad + font.getmetrics()[0]
    d.text((pad, base), ch, font=font, fill=255, anchor="ls")
    adv = int(round(font.getlength(ch)))
    bw = img.point(lambda v: 255 if v > 127 else 0)
    box = bw.getbbox()
    if not box:
        return b"", (0, 0, adv, 0, 0)
    x0, y0, x1, y1 = box
    w, h = x1 - x0, y1 - y0
    px = bw.load()
    bits = []
    for y in range(y0, y1):
        for x in range(x0, x1):
            bits.append(1 if px[x, y] else 0)
    while len(bits) % 8:
        bits.append(0)
    data = bytes(int("".join(map(str, bits[i:i + 8])), 2) for i in range(0, len(bits), 8))
    return data, (w, h, adv, x0 - pad, y0 - base)


def main():
    out = ["// Generated by tools/make_fonts.py from DejaVu Sans (free license). Do not edit.",
           "#pragma once", "#include <Adafruit_GFX.h>", ""]
    for cname, file, size in FONTS:
        font = ImageFont.truetype(find(file), size)
        bitmap, glyphs = bytearray(), []
        for code in range(FIRST, LAST + 1):
            ch = chr(code) if code < 0x7F else (None if code == 0x7F else EXTRA[code - 0x80])
            data, m = glyph_for(font, ch)
            if len(m) == 5:
                w, h, adv, xo, yo = m
            else:
                w, h, adv, xo, yo = 0, 0, 0, 0, 0
            glyphs.append((len(bitmap), w, h, adv, xo, yo))
            bitmap += data
        asc, desc = font.getmetrics()
        out.append(f"const uint8_t {cname}_bmp[] PROGMEM = {{")
        for i in range(0, len(bitmap), 24):
            out.append("  " + ",".join(f"0x{b:02X}" for b in bitmap[i:i + 24]) + ",")
        out.append("};")
        out.append(f"const GFXglyph {cname}_gly[] PROGMEM = {{")
        for g in glyphs:
            out.append("  {%d,%d,%d,%d,%d,%d}," % g)
        out.append("};")
        out.append(f"const GFXfont {cname} PROGMEM = {{(uint8_t*){cname}_bmp, (GFXglyph*){cname}_gly, "
                   f"0x{FIRST:02X}, 0x{LAST:02X}, {asc + desc}}};")
        out.append(f"#define {cname}_ASC {asc}")
        out.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print("wrote", os.path.normpath(OUT), f"({len(FONTS)} fonts)")


if __name__ == "__main__":
    main()
